"""Verify Phase 1.5c parameters and compare with previous phases."""
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

from planner.adaptive_params import get_adaptive_params

print("=" * 80)
print("Phase 1.5c Parameter Verification")
print("=" * 80)
print()

print("Current Phase 1.5c Parameters:")
print("-" * 80)

for scale in ['small', 'medium', 'large']:
    params = get_adaptive_params(scale)
    print(f"\n{scale.upper()}:")
    print(f"  alpha:                  {params.alpha}")
    print(f"  epsilon_min:            {params.epsilon_min}")
    print(f"  stagnation_ratio:       {params.stagnation_ratio}")
    print(f"  deep_stagnation_ratio:  {params.deep_stagnation_ratio}")

print()
print("=" * 80)
print("Phase Comparison (Phase 1 → Phase 1.5 → Phase 1.5c)")
print("=" * 80)
print()

print("SMALL (保持稳定):")
print("  Phase 1:   α=0.30, ε_min=0.05, stag=0.15")
print("  Phase 1.5: α=0.35, ε_min=0.08, stag=0.12")
print("  Phase 1.5c: α=0.35, ε_min=0.08, stag=0.12  ← 保持不变")
print()

print("MEDIUM (继续优化):")
print("  Phase 1:   α=0.20, ε_min=0.10, stag=0.25")
print("  Phase 1.5: α=0.30, ε_min=0.12, stag=0.18")
print("  Phase 1.5c: α=0.35, ε_min=0.12, stag=0.15  ← ⬆️ α, ⬇️ stag")
print()

print("LARGE (超保守，防止崩溃):")
print("  Phase 1:   α=0.15, ε_min=0.15, stag=0.35")
print("  Phase 1.5: α=0.25, ε_min=0.15, stag=0.22  ← 导致Seed 2034崩溃")
print("  Phase 1.5c: α=0.12, ε_min=0.15, stag=0.40  ← ⬇️ α, ⬆️ stag (超保守)")
print()

print("=" * 80)
print("Key Insights")
print("=" * 80)
print()
print("✅ SMALL: 保持稳定表现")
print()
print("✅ MEDIUM: 继续激进优化")
print("   - α 0.30→0.35: 更快学习以追赶Matheuristic")
print("   - stag 0.18→0.15: 更早使用LP修复")
print()
print("✅ LARGE: 超保守策略防止崩溃")
print("   - α 0.25→0.12: 比Phase 1更低，防止Q值震荡")
print("   - stag 0.22→0.40: 比Phase 1更高，给予更多探索时间")
print("   - 目标: 避免Seed 2034的灾难性崩溃 (4.45%)")
print()

print("=" * 80)
print("Expected Improvements")
print("=" * 80)
print()
print("Seed 2027:")
print("  Medium: 36.50% → 40-42% (接近Matheuristic 48%)")
print("  Large:  30.30% → 34-36% (恢复到Phase 1水平)")
print()
print("Seed 2031:")
print("  Medium: 40.12% → 44-46% (接近Matheuristic 54%)")
print("  Large:  27.93% → 20-25% (可能略降但稳定)")
print()
print("Seed 2034:")
print("  Medium: 38.00% → 38-40% (保持或略升)")
print("  Large:  4.45% → 28-32% (关键恢复！)")
print()

print("=" * 80)
print("Next Steps")
print("=" * 80)
print()
print("1. Test critical seeds:")
print("   python scripts/generate_alns_visualization.py --seed 2027")
print("   python scripts/generate_alns_visualization.py --seed 2031")
print("   python scripts/generate_alns_visualization.py --seed 2034")
print()
print("2. Success criteria:")
print("   ✅ Seed 2034 Large > 25% (avoid collapse)")
print("   ✅ Seed 2027 Large > 33% (maintain stability)")
print("   ✅ Medium scale: gap with Matheuristic < 8%")
print()
print("3. If successful, run full 10-seed test")
print()
print("=" * 80)
